apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: rddeepak/helloworld:latest
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
     name: myervice
     labels:
        app: nodeapp
spec:
    selector:
        app: nodeapp
    type: LoadBalancer
    ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
